Featured collection with variants card
summit-webapp-themes/demo-theme pull request #90
Opened 2024-12-05 11:23 UTC by NikitaD8848

1. Featured collection variants added

2024-12-06 06:13 UTC, karan1633 requested changes
Please do the needful changes

2024-12-06 06:13 UTC, karan1633 commented on components/ButtonComponent/VariantProductCardsButton.tsx
Why do we have a link tag? Can't it be a button ?

2024-12-06 06:13 UTC, karan1633 commented on components/HomePage/FeaturedCollections/FeaturedCollectionWithVariantColour/FeaturedCollectionWithVariantProductCardColour.tsx
Please provide types to the file.

2024-12-06 06:13 UTC, karan1633 commented on cards/ProductCardVariantColour.tsx
Please add types.

2024-12-06 06:13 UTC, karan1633 commented on components/HomePage/FeaturedCollections/FeaturedCollectionWithVariantColour/FeaturedCollectionWithVariantColourCardContainer.tsx
Please add types.

2024-12-06 07:27 UTC, NikitaD8848 commented on components/ButtonComponent/VariantProductCardsButton.tsx
Link removed.

2024-12-06 07:28 UTC, NikitaD8848 commented on components/HomePage/FeaturedCollections/FeaturedCollectionWithVariantColour/FeaturedCollectionWithVariantProductCardColour.tsx
Done.

2024-12-06 07:28 UTC, NikitaD8848 commented on cards/ProductCardVariantColour.tsx
Done.

2024-12-06 07:28 UTC, NikitaD8848 commented on components/HomePage/FeaturedCollections/FeaturedCollectionWithVariantColour/FeaturedCollectionWithVariantColourCardContainer.tsx
Done.

2024-12-08 17:16 UTC, karan1633 requested changes

2024-12-08 17:16 UTC, karan1633 commented on components/HomePage/FeaturedCollections/FeaturedCollectionWithVariantColour/FeaturedCollectionWithVariantProductCardColour.tsx
Hey, great job there adding types to your code!! I highly appreciate it!
A small request to end your types variable with consistent naming convention. Here in this file, it could be ProductPropsTypes and AttributesTypes. This way it clearly signifies the existence of that variable.

2024-12-08 17:16 UTC, karan1633 commented on components/HomePage/FeaturedCollections/FeaturedCollectionWithVariantColour/FeaturedCollectionWithVariantColourCardContainer.tsx
I can see you have added types to map fn which is noteworthy and highly commendable. I hope you continue doing this practise!
It could have been much better if you would have define the types of props that you are sending. Please name the type variable as "<component_name_according_to_you>PropTypes"

2024-12-08 17:16 UTC, karan1633 commented on cards/ProductCardVariantColour.tsx
Please rename Props variable to something that sounds more relevant. Read further comments you will be able to understand very clearly.

2024-12-08 17:18 UTC, karan1633 requested changes
Please make the requested changes ASAP. Keep up the good work!

2024-12-09 04:56 UTC, NikitaD8848 commented on components/HomePage/FeaturedCollections/FeaturedCollectionWithVariantColour/FeaturedCollectionWithVariantProductCardColour.tsx
Thank you for the appreciation! I've updated the type variables to follow a consistent naming convention, such as ProductPropsTypes and AttributesTypes, to make them more clear and aligned. Let me know if there’s anything else!

2024-12-09 04:56 UTC, NikitaD8848 commented on cards/ProductCardVariantColour.tsx
The changes have been made. I've renamed the Props variable to something more relevant and addressed the other comments as well. Let me know if there's anything else to adjust!

2024-12-09 04:57 UTC, NikitaD8848 commented on components/HomePage/FeaturedCollections/FeaturedCollectionWithVariantColour/FeaturedCollectionWithVariantColourCardContainer.tsx
Thank you so much for the encouraging words! I'm glad the improvements are noticeable. I’ll ensure to define the types for the props being passed and name the type variable as <ComponentName>PropTypes for better clarity and consistency. I'll keep up with this practice moving forward!

2024-12-09 05:20 UTC, karan1633 approved these changes

2024-12-09 05:20 UTC, merged